language: r
install:
  - R -e "install.packages('devtools')"
  - R -e "devtools::install_github('jimhester/lintr')"
script:
  - tools/lint.R | grep "style:" ; if [ $? -ne 1 ]; then exit 1; fi

notifications:
  email: true
