language: r
install:
  - R -e "install.packages('devtools')"
  - R -e "devtools::install_github('jimhester/lintr')"
script:
  - ./lint.R | grep style ; if [ $? -ne 1 ]; then exit 1; fi

notifications:
  email: true

#language: r
#cache: packages

#r:
  #- oldrel
  #- release
  #- devel

#r_github_packages:
  #- jimhester/lintr

